{"name": "test_sub_003", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_1st_file.Test_my001 object at 0x000002600255C1D0>\n\n    def test_sub_003(self):\n        a= 10\n        b= 5\n        sub= a-b\n        print(\"Sub of a and b :\", sub)\n        if sub == 6:\n            assert True\n        else:\n>           assert False\nE           assert False\n\nPytest_my\\test_1st_file.py:38: AssertionError"}, "start": 1690620324950, "stop": 1690620324950, "uuid": "efb9f050-b29e-44b4-ba69-1ae3690be666", "historyId": "b4a16c17f935adfff31f2aaa4a88f0b1", "testCaseId": "b4a16c17f935adfff31f2aaa4a88f0b1", "fullName": "Pytest_my.test_1st_file.Test_my001#test_sub_003", "labels": [{"name": "parentSuite", "value": "Pytest_my"}, {"name": "suite", "value": "test_1st_file"}, {"name": "subSuite", "value": "Test_my001"}, {"name": "host", "value": "DESKTOP-QRGRBTF"}, {"name": "thread", "value": "8256-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "Pytest_my.test_1st_file"}]}